### PR TITLE
Confirm to `ObservableObject`

### PR DESCRIPTION
**Pull request by Alja7dali**
Being able to use `@ObservedObject` or `@StateObject`!

### CODE REVIEW

**Review by stonko1994 — COMMENTED** [review]
Thank you for contributing.

May I ask what is the intention/need behind conforming the `SimultaneouslyScrollViewHandler` to `ObservableObject`?

**Comment by Alja7dali** [comment]
In my case, I needed to observe the changes made by the factory. Thus, it was the only option for me by making `SimultaneouslyScrollViewHandler` confirm to `ObservableObject`.

**Comment by stonko1994** [comment]
You should be able to achieve this by using the publisher direct. Something like the following should work:

Create an instance variable of `SimultaneouslyScrollViewHandler`
```swfit
private let simultaneouslyScrollViewHandler: SimultaneouslyScrollViewHandler
```

Assign the `simultaneouslyScrollViewHandler` either by Dependency Injection or create one using the factory
```swift
self.simultaneouslyScrollViewHandler = simultaneouslyScrollViewHandler
// or
self.simultaneouslyScrollViewHandler = SimultaneouslyScrollViewHandlerFactory.create()
```

Subscribe to the `scrolledToBottomPublisher` using pure Combine features
```swift
self.simultaneouslyScrollViewHandler.scrolledToBottomPublisher
    .removeDuplicates()
    .sink { [self] newValue in
        // Use the new value e.g. for assigning it to a `@State` if you are inside a View.
        withAnimation {
            isScrollBottomReached = newValue
        }
    }
    .store(in: &cancelableSet)
```

For the cancellable, you need to create some kind of collection to retain it.
```swift
private var cancelableSet: [AnyCancellable] = []
```

This is not as convenient as `ObservableObject` but it still gives you full flexibility (which was my aim in first place)

**Comment by stonko1994** [comment]
Closing due to inactivity. Feel free to add additional comments if this is still a topic.

**Pull request closed without merging**
